export const upperLetters = [
  { l: 'a', bg: '#ffb3ba' },
  { l: 'b', bg: '#ffdfba' },
  { l: 'c', bg: '#ffffba' },
  { l: 'd', bg: '#baffc9' },
  { l: 'e', bg: '#bae1ff' },
  { l: 'f', bg: '#E0BBE4' },
  { l: 'g', bg: '#80e5a6' },
  { l: 'h', bg: '#e1ffe9' },
  { l: 'i', bg: '#e5e5e5' },
  { l: 'j', bg: '#FFDFD3' },
  { l: 'k', bg: '#FEC8D8' },
  { l: 'l', bg: '#f3f4de' },
  { l: 'm', bg: '#ffe0ba' },
  { l: 'n', bg: '#e9dafd' },
  { l: 'o', bg: '#957DAD' },
  { l: 'p', bg: '#e0f2f2' },
  { l: 'q', bg: '#ffb9b9' },
  { l: 'r', bg: '#d2eaff' },
  { l: 's', bg: '#caffde' },
  { l: 't', bg: '#D291BC' },
  { l: 'u', bg: '#ffdddd' },
  { l: 'v', bg: '#fff9b9' },
  { l: 'w', bg: '#90f0b4' },
  { l: 'x', bg: '#ffcbb9' },
  { l: 'y', bg: '#cfd0e1' },
  { l: 'z', bg: '#94ffbb' }
]

export const lowerLetters = [
  { l: 'a', bg: '#ffb3ba' },
  { l: 'b', bg: '#ffdfba' },
  { l: 'c', bg: '#ffffba' },
  { l: 'd', bg: '#baffc9' },
  { l: 'e', bg: '#bae1ff' },
  { l: 'f', bg: '#E0BBE4' },
  { l: 'g', bg: '#80e5a6' },
  { l: 'h', bg: '#e1ffe9' },
  { l: 'i', bg: '#e5e5e5' },
  { l: 'j', bg: '#FFDFD3' },
  { l: 'k', bg: '#FEC8D8' },
  { l: 'l', bg: '#f3f4de' },
  { l: 'm', bg: '#ffe0ba' },
  { l: 'n', bg: '#e9dafd' },
  { l: 'o', bg: '#957DAD' },
  { l: 'p', bg: '#e0f2f2' },
  { l: 'q', bg: '#ffb9b9' },
  { l: 'r', bg: '#d2eaff' },
  { l: 's', bg: '#caffde' },
  { l: 't', bg: '#D291BC' },
  { l: 'u', bg: '#ffdddd' },
  { l: 'v', bg: '#fff9b9' },
  { l: 'w', bg: '#90f0b4' },
  { l: 'x', bg: '#ffcbb9' },
  { l: 'y', bg: '#cfd0e1' },
  { l: 'z', bg: '#94ffbb' }
]
