export const upperLetters = [
  { l: require('../../assets/images/A.png'), bg: '#ffb3ba' },
  { l: require('../../assets/images/B.png'), bg: '#ffdfba' },
  { l: require('../../assets/images/C.png'), bg: '#ffffba' },
  { l: require('../../assets/images/D.png'), bg: '#baffc9' },
  { l: require('../../assets/images/E.png'), bg: '#bae1ff' },
  { l: require('../../assets/images/F.png'), bg: '#E0BBE4' },
  { l: require('../../assets/images/G.png'), bg: '#80e5a6' },
  { l: require('../../assets/images/H.png'), bg: '#e1ffe9' },
  { l: require('../../assets/images/I.png'), bg: '#e5e5e5' },
  { l: require('../../assets/images/J.png'), bg: '#FFDFD3' },
  { l: require('../../assets/images/K.png'), bg: '#FEC8D8' },
  { l: require('../../assets/images/L.png'), bg: '#f3f4de' },
  { l: require('../../assets/images/M.png'), bg: '#ffe0ba' },
  { l: require('../../assets/images/N.png'), bg: '#e9dafd' },
  { l: require('../../assets/images/O.png'), bg: '#957DAD' },
  { l: require('../../assets/images/P.png'), bg: '#e0f2f2' },
  { l: require('../../assets/images/Q.png'), bg: '#ffb9b9' },
  { l: require('../../assets/images/R.png'), bg: '#d2eaff' },
  { l: require('../../assets/images/S.png'), bg: '#caffde' },
  { l: require('../../assets/images/T.png'), bg: '#D291BC' },
  { l: require('../../assets/images/U.png'), bg: '#ffdddd' },
  { l: require('../../assets/images/V.png'), bg: '#fff9b9' },
  { l: require('../../assets/images/W.png'), bg: '#90f0b4' },
  { l: require('../../assets/images/Y.png'), bg: '#ffcbb9' },
  { l: require('../../assets/images/X.png'), bg: '#cfd0e1' },
  { l: require('../../assets/images/Z.png'), bg: '#94ffbb' }
]

export const lowerLetters = [
  { l: require('../../assets/images/A.png'), bg: '#ffb3ba' },
  { l: require('../../assets/images/B.png'), bg: '#ffdfba' },
  { l: require('../../assets/images/C.png'), bg: '#ffffba' },
  { l: require('../../assets/images/D.png'), bg: '#baffc9' },
  { l: require('../../assets/images/E.png'), bg: '#bae1ff' },
  { l: require('../../assets/images/F.png'), bg: '#E0BBE4' },
  { l: require('../../assets/images/G.png'), bg: '#80e5a6' },
  { l: require('../../assets/images/H.png'), bg: '#e1ffe9' },
  { l: require('../../assets/images/I.png'), bg: '#e5e5e5' },
  { l: require('../../assets/images/J.png'), bg: '#FFDFD3' },
  { l: require('../../assets/images/K.png'), bg: '#FEC8D8' },
  { l: require('../../assets/images/L.png'), bg: '#f3f4de' },
  { l: require('../../assets/images/M.png'), bg: '#ffe0ba' },
  { l: require('../../assets/images/N.png'), bg: '#e9dafd' },
  { l: require('../../assets/images/O.png'), bg: '#957DAD' },
  { l: require('../../assets/images/P.png'), bg: '#e0f2f2' },
  { l: require('../../assets/images/Q.png'), bg: '#ffb9b9' },
  { l: require('../../assets/images/R.png'), bg: '#d2eaff' },
  { l: require('../../assets/images/S.png'), bg: '#caffde' },
  { l: require('../../assets/images/T.png'), bg: '#D291BC' },
  { l: require('../../assets/images/U.png'), bg: '#ffdddd' },
  { l: require('../../assets/images/V.png'), bg: '#fff9b9' },
  { l: require('../../assets/images/W.png'), bg: '#90f0b4' },
  { l: require('../../assets/images/Y.png'), bg: '#ffcbb9' },
  { l: require('../../assets/images/X.png'), bg: '#cfd0e1' },
  { l: require('../../assets/images/Z.png'), bg: '#94ffbb' }
]
